version: '2'
services:

    storage:
        image: busybox:1.25

    mysql:
        image: mysql:5.7
        volumes_from:
            - storage
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress

    wordpress:
        build: ./services/wordpress
        links:
            - mysql:mysql
        ports:
            - ${HUMBLE_PORT}:80
        volumes_from:
            - storage
        environment:
            - WORDPRESS_DB_PASSWORD=root

    # this definition has linked volumes so we can work on the scripts
    humble:
        build: ../../image
        volumes_from:
            - storage
        env_file:
            - .env
        volumes:
            - ./data:/data
            - ../../image/scripts:/scripts
