version: '2'
services:

    pma:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8081:80
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
