version: '2'
services:

    blog:
        image: wordpress
        links:
            - mysql:mysql
        ports:
            - ${PROJECT_PORT}:80
        environment:
            - WORDPRESS_DB_PASSWORD=root

    mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress

    # this definition has linked volumes so we can work on the scripts
    humble:
        build: ../../image
        volumes:
            - ./data:/data
            - ../../image/scripts:/scripts
